"""Initial migration

Revision ID: d140fcb20d4f
Revises: 3615fb6a69b5
Create Date: 2023-06-09 16:09:24.812230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd140fcb20d4f'
down_revision = '3615fb6a69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_details', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
